<h1 style="text-align:left;color:brown">
    NumPy
</h1>
<span style="float:right;font-size:medium"><tt>Code by : Jayadev Patil</tt></span>

## <u><strong>Numpy</strong></u><span style="float:right;font-size:medium"><a href='https://github.com/jayadevnpatil'>github</a></span>
This notebook covers **array indexing** and **array slicing**

In [1]:
import numpy as np
print(np.__version__)

1.26.3


### Array Indexing

Array indexing refers to the process of accessing elements within a NumPy array

#### Basic indexing

In [2]:
# 1D Array
arr = np.array([1,2,3,4,5])

# element on index 4
print(arr[4])

5


In [3]:
# 2D Array
arr = np.array([[1, 2],
                [3, 4]])

# element on row:1 and col:0
print(arr[1,0])

3


In [4]:
# 3D Array
arr = np.array([[[ 1,  2,  3],
                 [ 4,  5,  6]],
                [[ 7,  8,  9],
                 [10, 11, 12]]])
print(arr.shape)

# element at index (1, 0, 2)
print(arr[1, 0, 2])

(2, 2, 3)
9


In [5]:
# Negative indexing
arr = np.array([1,2,3,4,5])

# element on index -2
print(arr[-2])

4


In [6]:
# Boolean indexing
arr = np.array([1, 2, 3, 4, 5])

mask = arr > 3
print(mask)
print(arr[mask])

[False False False  True  True]
[4 5]


### Array Slicing

Array slicing in NumPy refers to the process of extracting a subset of elements from a NumPy array based on specified start, stop, and step parameters.

<strong><tt>array[start:stop:step]</strong></tt>

- **start**: The index indicating the start of the slice. If not provided, slicing starts from the beginning of the array.
  
- **stop**: The index indicating the end of the slice. The slice will not include this index. If not provided, slicing goes to the end of the array

- **step** : The step size used to increment the index while slicing. If not provided, the default step size is

In [7]:
# 1D Array Slicing
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slicing to get a subset of elements
print(arr[2:7])

# Slicing with step
print(arr[1:9:2])

# Slicing from the beginning
print(arr[:5])

# Slicing to the end
print(arr[5:])

# Slicing with negative indices
print(arr[-5:-2])

[2 3 4 5 6]
[1 3 5 7]
[0 1 2 3 4]
[5 6 7 8 9]
[5 6 7]


In [8]:
arr = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# taking the subset of rows and columns
print(arr[0:2, 1:3])

# Slicing with step
print(arr[::2, ::2])

[[2 3]
 [5 6]]
[[1 3]
 [7 9]]
