<h1 style="text-align:left;color:brown">
    NumPy
</h1>
<span style="float:right;font-size:medium"><tt>Code by : Jayadev Patil</tt></span>

## <u><strong>Numpy</strong></u><span style="float:right;font-size:medium"><a href='https://github.com/jayadevnpatil'>github</a></span>
This notebook covers **elementwise operations** over the arrays
* Elementwise addition, subtraction, multiplication, division, exponentiation
* Matrix Multiplication
* Dot Product

In [1]:
import numpy as np

As a basic exercise we create multi dimensional arrays as below

In [2]:
np.arange(10).reshape(10) # 1d array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(12).reshape(3,4) # 2d array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.arange(24).reshape(2,3,4) # 3d array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Element-wise Operations

In [5]:
# Declaration of arrays

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[4, 5],
                 [6, 7]])

NumPy allows you to perform a wide range of arithmetic operations on arrays. Here are some common arithmetic operations:

In [6]:
# Element-wise addition

sum = arr1 + arr2
print(sum)

[[ 5  7]
 [ 9 11]]


In [7]:
# Element-wise subtraction

diff = arr2 - arr1
print(diff)

[[3 3]
 [3 3]]


In [8]:
# Element-wise multiplication

prod = arr1 * arr2
print(prod)

[[ 4 10]
 [18 28]]


In [9]:
# Element-wise division

result = arr1 / arr2
print(result)

[[0.25       0.4       ]
 [0.5        0.57142857]]


In [10]:
# Element-wise exponentiation

result = arr1 ** arr2
print(result) 

[[    1    32]
 [  729 16384]]


In [11]:
# Matrix Multiplication (defined between two matrices.)

# 1st element : (1*4)+(2*6) = 16
# 2nd element : (1*5)+(2*7) = 19
# 3rd element : (3*4)+(4*6) = 36
# 4th element : (3*5)+(4*7) = 43

matrix_prod = np.matmul(arr1, arr2)
print(matrix_prod)

[[16 19]
 [36 43]]


In [12]:
# Dot Product (defined between two vectors)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_prod = np.dot(arr1, arr2)
print(dot_prod)

32
